import type { PlanDefinition } from "./review-types"

export const plan: PlanDefinition = {
  id: "task-management",
  version: "3.0.0",
  title: "Task completion, in scope",
  description: "Illustrative baseline: replace status strings with a completed flag, tighten titles, and add explicit completion contracts. Unchanged declarations remain visible as context.",
  stories: [
    { id: "story.create-task", label: "Create a task", outcome: "Every valid task title creates one visible incomplete task." },
    { id: "story.list-tasks", label: "See my tasks", outcome: "Every stored task appears in its stored order." },
    { id: "story.complete-task", label: "Complete a task", outcome: "Completing a task keeps it visible with completed state." },
  ],
  storyTests: [
    { id: "test.create-task", label: "creates every valid generated task as incomplete", storyId: "story.create-task", fileId: "file.test.create-task", relativePath: "src/story-tests/create-task.test.ts", proposedCodeIds: ["code.create-input", "code.create-task", "code.list-tasks"] },
    { id: "test.list-tasks", label: "lists every generated fixture in its stored order", storyId: "story.list-tasks", fileId: "file.test.list-tasks", relativePath: "src/story-tests/list-tasks.test.ts", proposedCodeIds: ["code.tasks", "code.list-tasks"] },
    { id: "test.complete-task", label: "completes every generated incomplete task without removing it", storyId: "story.complete-task", fileId: "file.test.complete-task", relativePath: "src/story-tests/complete-task.test.ts", proposedCodeIds: ["code.create-input", "code.complete-input", "code.create-task", "code.complete-task", "code.list-tasks"] },
    { id: "test.missing-task", label: "fails for every generated missing task id", storyId: "story.complete-task", fileId: "file.test.missing-task", relativePath: "src/story-tests/missing-task.test.ts", proposedCodeIds: ["code.complete-input", "code.complete-task"], assertedErrorIds: ["code.task-not-found"] },
  ],
  currentCode: [
    { id: "code.task-id", category: "Schema", label: "TaskId", fileId: "file.current.task", relativePath: "src/current/task.ts", symbol: "TaskId", scope: "Task model" },
    { id: "code.task-title", category: "Schema", label: "TaskTitle", fileId: "file.current.task", relativePath: "src/current/task.ts", symbol: "TaskTitle", scope: "Task model" },
    { id: "code.task-status", category: "Schema", label: "TaskStatus", fileId: "file.current.task", relativePath: "src/current/task.ts", symbol: "TaskStatus", scope: "Task model", rationale: "Status strings are replaced by the completed field on Task." },
    { id: "code.task", category: "Schema", label: "Task", fileId: "file.current.task", relativePath: "src/current/task.ts", symbol: "Task", scope: "Task model", dependencyIds: ["code.task-id", "code.task-title", "code.task-status"] },
    { id: "code.tasks", category: "Schema", label: "Tasks", fileId: "file.current.task", relativePath: "src/current/task.ts", symbol: "Tasks", scope: "Task model", dependencyIds: ["code.task"] },
    { id: "code.create-input", category: "Schema", label: "CreateTaskInput", fileId: "file.current.task", relativePath: "src/current/task.ts", symbol: "CreateTaskInput", scope: "Task model", dependencyIds: ["code.task-title"] },
    { id: "code.task-service-shape", category: "Interface", label: "TaskServiceShape", fileId: "file.current.task-service", relativePath: "src/current/task-service.ts", symbol: "TaskServiceShape", scope: "Task service", dependencyIds: ["code.create-input", "code.task", "code.tasks"] },
    { id: "code.task-service", category: "Service", label: "TaskService", fileId: "file.current.task-service", relativePath: "src/current/task-service.ts", symbol: "TaskService", scope: "Task service", dependencyIds: ["code.task-service-shape"] },
    { id: "code.create-task", category: "EffectfulFunction", label: "createTask", fileId: "file.current.task-service", relativePath: "src/current/task-service.ts", symbol: "createTask", scope: "Task service", contract: { inputSchemaIds: ["code.create-input"], successSchemaId: "code.task", errorIds: [], serviceIds: ["code.task-service"] } },
    { id: "code.list-tasks", category: "EffectfulFunction", label: "listTasks", fileId: "file.current.task-service", relativePath: "src/current/task-service.ts", symbol: "listTasks", scope: "Task service", contract: { inputSchemaIds: [], successSchemaId: "code.tasks", errorIds: [], serviceIds: ["code.task-service"] } },
  ],
  proposedCode: [
    { id: "code.task-id", category: "Schema", label: "TaskId", fileId: "file.task", relativePath: "src/domain/task.ts", symbol: "TaskId", scope: "Task model" },
    { id: "code.task-title", category: "Schema", label: "TaskTitle", fileId: "file.task", relativePath: "src/domain/task.ts", symbol: "TaskTitle", scope: "Task model", rationale: "Titles are limited to 80 characters instead of 120; longer existing values need a migration decision." },
    { id: "code.task", category: "Schema", label: "Task", fileId: "file.task", relativePath: "src/domain/task.ts", symbol: "Task", scope: "Task model", dependencyIds: ["code.task-id", "code.task-title"], rationale: "Replace the status string with an explicit completion flag. Existing records need conversion." },
    { id: "code.tasks", category: "Schema", label: "Tasks", fileId: "file.task", relativePath: "src/domain/task.ts", symbol: "Tasks", scope: "Task model", dependencyIds: ["code.task"] },
    { id: "code.create-input", category: "Schema", label: "CreateTaskInput", fileId: "file.task", relativePath: "src/domain/task.ts", symbol: "CreateTaskInput", scope: "Task model", dependencyIds: ["code.task-title"] },
    { id: "code.complete-input", category: "Schema", label: "CompleteTaskInput", fileId: "file.task", relativePath: "src/domain/task.ts", symbol: "CompleteTaskInput", scope: "Task model", dependencyIds: ["code.task-id"], rationale: "Completion accepts a task identity without copying the full task." },
    { id: "code.task-not-found", category: "Error", label: "TaskNotFound", fileId: "file.task", relativePath: "src/domain/task.ts", symbol: "TaskNotFound", scope: "Task model", dependencyIds: ["code.task-id"], rationale: "A missing task is an explicit failure contract." },
    { id: "code.task-service-shape", category: "Interface", label: "TaskServiceShape", fileId: "file.task-service", relativePath: "src/domain/task-service.ts", symbol: "TaskServiceShape", scope: "Task service", dependencyIds: ["code.create-input", "code.complete-input", "code.task", "code.tasks", "code.task-not-found"], rationale: "Add completion to the service interface alongside create and list." },
    { id: "code.task-service", category: "Service", label: "TaskService", fileId: "file.task-service", relativePath: "src/domain/task-service.ts", symbol: "TaskService", scope: "Task service", dependencyIds: ["code.task-service-shape"] },
    { id: "code.create-task", category: "EffectfulFunction", label: "createTask", fileId: "file.task-service", relativePath: "src/domain/task-service.ts", symbol: "createTask", scope: "Task service", contract: { inputSchemaIds: ["code.create-input"], successSchemaId: "code.task", errorIds: [], serviceIds: ["code.task-service"] } },
    { id: "code.list-tasks", category: "EffectfulFunction", label: "listTasks", fileId: "file.task-service", relativePath: "src/domain/task-service.ts", symbol: "listTasks", scope: "Task service", contract: { inputSchemaIds: [], successSchemaId: "code.tasks", errorIds: [], serviceIds: ["code.task-service"] } },
    { id: "code.complete-task", category: "EffectfulFunction", label: "completeTask", fileId: "file.task-service", relativePath: "src/domain/task-service.ts", symbol: "completeTask", scope: "Task service", contract: { inputSchemaIds: ["code.complete-input"], successSchemaId: "code.task", errorIds: ["code.task-not-found"], serviceIds: ["code.task-service"] }, rationale: "Expose completion with Task success, TaskNotFound failure, and TaskService requirements." },
  ],
}
